# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_earned_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
