# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171116_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.FloatField(),
        ),
    ]
