# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171208_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
