# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20171010_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_entered',
            field=models.DateTimeField(),
        ),
    ]
