# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20171010_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock',
        ),
    ]
