# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_user_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_stock',
            name='date_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_stock',
            name='date_bought',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
