# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20171017_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stock',
            name='stock_curr_type',
            field=models.CharField(max_length=10),
        ),
    ]
