# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20171017_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
