# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_auto_20171031_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyreceipt',
            name='date_bought',
        ),
    ]
