# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_remove_buyreceipt_date_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyreceipt',
            name='date_bought',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
