# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_buyreceipt_date_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='supply',
        ),
        migrations.AddField(
            model_name='buyreceipt',
            name='total_cost',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
