# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_auto_20171101_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyreceipt',
            name='total_cost',
        ),
    ]
