# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_remove_buyreceipt_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_stock',
            name='price_bought_at',
        ),
    ]
