# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_auto_20171102_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('curr_type', models.CharField(max_length=10, unique=True)),
                ('date_entered', models.DateTimeField()),
            ],
        ),
    ]
