# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_user_stock_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stock',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
