# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0025_remove_user_stock_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_price_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField()),
                ('coin_name', models.CharField(max_length=10, unique=True)),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('mktcap', models.FloatField()),
            ],
        ),
    ]
