# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0026_current_price_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current_price_table',
            old_name='coin_name',
            new_name='coin_type',
        ),
        migrations.RenameField(
            model_name='current_price_table',
            old_name='date_entered',
            new_name='time',
        ),
    ]
