# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0027_auto_20171109_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_price_table',
            name='time',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M'),
        ),
    ]
