# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0029_auto_20171109_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
                ('coin_type', models.CharField(max_length=10, unique=True)),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('mktcap', models.FloatField()),
            ],
        ),
    ]
