# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0030_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='coin_type',
            field=models.CharField(max_length=10),
        ),
    ]
