# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0032_auto_20171109_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyreceipt',
            old_name='curr_type',
            new_name='coin_type',
        ),
    ]
