# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0033_auto_20171109_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_stock',
            old_name='stock_curr_type',
            new_name='coin_type',
        ),
    ]
