# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0034_auto_20171109_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyreceipt',
            name='units',
            field=models.FloatField(),
        ),
    ]
