# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0035_auto_20171110_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellreceipt',
            name='units',
            field=models.FloatField(),
        ),
    ]
