# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0036_auto_20171110_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_stock',
            name='netgain',
            field=models.IntegerField(default=0),
        ),
    ]
