# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0037_user_stock_netgain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stock',
            name='netgain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
