# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0038_auto_20171116_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stock',
            name='netgain',
            field=models.FloatField(default=0.0),
        ),
    ]
