# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0039_auto_20171116_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stock',
            name='units',
            field=models.FloatField(),
        ),
    ]
