# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0041_auto_20171116_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyreceipt',
            name='buy_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sellreceipt',
            name='sell_total',
            field=models.FloatField(null=True),
        ),
    ]
