# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0042_auto_20171116_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
