# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0043_auto_20171208_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyreceipt',
            name='buy_total',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='buyreceipt',
            name='price_bought_at',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='current_price_table',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='history',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historystock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='sellreceipt',
            name='price_sold_at',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='sellreceipt',
            name='sell_total',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
    ]
