# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0044_auto_20171208_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyreceipt',
            name='units',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sellreceipt',
            name='units',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='user_stock',
            name='units',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
    ]
