# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0045_auto_20171208_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stock',
            name='netgain',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
