# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0046_auto_20171208_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_price_table',
            name='mktcap',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='current_price_table',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='mktcap',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
